### ISSUE TITLE
when looking to support an existing request the request page it goes to is undefinend

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#358]
### Expected Behavior

* I get to the request for that article

### Actual Behavior

* takes me to /request/undefined

### Steps to Reproduce this bug

* Run http://www.nejm.org/doi/full/10.1056/NEJM199901143400207 through the /request/new page

**Comment by JosephMcArthur** [comment]
The plugin couldn't find the existing request on this URL too

**Comment by JosephMcArthur** [comment]
my request url is http://oab.test.cottagelabs.com/request/uXGQEZJaJYRPA6PBm

**Comment by markmacgillivray** [comment]
These links have been fixed now.

**Comment by JosephMcArthur** [comment]
this is back in 1.7 & on current /request/new page

**Comment by markmacgillivray** [comment]
Fixed in the plugin but still to get to the website UI

**Comment by markmacgillivray** [comment]
Fixed again again again

**Comment by JosephMcArthur** [comment]
This will NOT stay closed >:(

Supporting: http://www.nejm.org/doi/full/10.1056/NEJMoa1504720 should add your support to: http://oab.test.cottagelabs.com/request/CLMPrDLk3Bwrd4ejB but it doesn't. This is with the plugin 0.2.1.

**Comment by markmacgillivray** [comment]
This seems to be working for me. The availability check on that URL takes a VERY long time, like two minutes, which appears to be mostly spent waiting for dissemin to return. But when it does return, I see the links to the support request and clicking it works. However you may be seeing problems because there are actually multiple requests for this article in the dev system, because at various points we have been able to break things and submit new requests where it should not be possible. I can clear out all the test requests we have created so far if you want. But as far as I can tell, this is fixed.

**Comment by JosephMcArthur** [comment]
Thanks for reopening this, I missed that. Also, thanks for clearing out the test data. Also, more info here, I'm still on 2.1. Worked through most of the ten requests we had, my results were:

* http://oab.test.cottagelabs.com/request/ZJXdCX65oD2xNKiCP was found by the find api \o/
* http://oab.test.cottagelabs.com/request/3u3xARjRsQoJzeniZ. Supported it, but was sent to undefined. The page now seem to have 2 supporters (but not extra story) & the plugin tells me I have supported it. 
* http://oab.test.cottagelabs.com/request/twpusXfduyaCPGm9e same again. 
* http://oab.test.cottagelabs.com/request/uDi3owjiczkTGEXdh the plugin finds no request at all
* http://oab.test.cottagelabs.com/request/GSKErWTMMamqJRSrk request found, but sent to undefined after supporting from the plugin. Page now has 2 supporters, but no extra stories or usernames. 
* http://oab.test.cottagelabs.com/request/Xp96FFrjAkbE5MkxE same again. Plugin tells me I've now supported the request after.

**Comment by markmacgillivray** [comment]
OK, they will all have to be reviewed tomorrow, then the plugin retested, then the bookmarklet finished. That puts the site release out to Wednesday at the earliest.

**Comment by JosephMcArthur** [comment]
Okay. I'm going to try and restart my mac & use a cleaner install of chrome. @chealsye @meganwaps can you try this?

**Comment by JosephMcArthur** [comment]
Okay, just did the above & still no luck.

**Comment by chealsye** [comment]
@JosephMcArthur Could you give me a link that already has a request? I can't support my own... so having trouble testing this.

**Comment by meganwaps** [comment]
I just tried to get this to work by supporting Chealsye's most recent request, Once I click on the 'Add your Support' button, nothing happens. It just looks like this forever. 
![screen shot 2016-10-24 at 12 54 19 pm](https://cloud.githubusercontent.com/assets/5968703/19661574/1b7bd1f4-99e9-11e6-9c38-b95b23dc1716.png)

**Comment by JosephMcArthur** [comment]
@chealsye  you can find the links to the original articles on request pages (they're the links for the titles)
> http://oab.test.cottagelabs.com/request/ZJXdCX65oD2xNKiCP was found by the find api \o/
http://oab.test.cottagelabs.com/request/3u3xARjRsQoJzeniZ. Supported it, but was sent to undefined. The page now seem to have 2 supporters (but not extra story) & the plugin tells me I have supported it.
http://oab.test.cottagelabs.com/request/twpusXfduyaCPGm9e same again.
http://oab.test.cottagelabs.com/request/uDi3owjiczkTGEXdh the plugin finds no request at all
http://oab.test.cottagelabs.com/request/GSKErWTMMamqJRSrk request found, but sent to undefined after supporting from the plugin. Page now has 2 supporters, but no extra stories or usernames.
http://oab.test.cottagelabs.com/request/Xp96FFrjAkbE5MkxE same again. Plugin tells me I've now supported the request after.

@meganwaps can you try to support the requests from the plugin. That's the issue here.

**Comment by JosephMcArthur** [comment]
> I just tried to get this to work by supporting Chealsye's most recent request, Once I click on the 'Add your Support' button, nothing happens. It just looks like this forever. 

I looked at this and it worked a-okay, can you try on some others?

**Comment by chealsye** [comment]
@JosephMcArthur Ah okay. I tried the links you included above, but all the ones I tried didn't have a request. Will try with others from the page.

**Comment by chealsye** [comment]
Tried to support http://www.cell.com/current-biology/abstract/S0960-9822(15)01167-7

got the undefined error.

![screen shot 2016-10-24 at 17 29 47](https://cloud.githubusercontent.com/assets/9299248/19664949/be4e3954-9a10-11e6-9da9-c065a7b49b86.png)


![screen shot 2016-10-24 at 17 29 59](https://cloud.githubusercontent.com/assets/9299248/19664946/bbdd6ed8-9a10-11e6-9e1c-d004e7629480.png)

**Comment by JosephMcArthur** [comment]
> > I just tried to get this to work by supporting Chealsye's most recent request, Once I click on the 'Add your Support' button, nothing happens. It just looks like this forever.

>I looked at this and it worked a-okay, can you try on some others?

@meganwaps we'd also need some info on browser to do this.

**Comment by markmacgillivray** [comment]
I have updated the plugin to 0.2.2 and made a new release as well. I have changed it so that it no longer shows a message about "you have already supported" or "you created". Instead, if the user did support or create, the big orange button just says "view request" and clicking that takes the user to the request page.

Other functionality is the same - if the item is already available, the button goes blue and clicking it will open the item. If it is unavailable, the button is orange and pressing it opens the box to add a story to add a new request. If it is unavailable but there is already a request created by someone else and the current user has not yet supported it, then pressing the button opens the story box but asks for a support story. In cases where the user submits a new request or a support story, on successful submission they see a thank you note and a link to the request page, which will also have been opened for them automatically.

I have tested this with the article at:

http://www.tandfonline.com/doi/abs/10.1080/09505431.2014.928678

I was able to support an existing request, then able to be told I already support it and to open the request, and then able to create a new request (for data this time) and have the proper new request page open, and then able to view the fact that there was already both an article and  a data request, and each button take me to either of the requests, and those requests display the fact that I either already supported or had created the request. Also the request page shows the support stories now (there was an error there).

@JosephMcArthur please test again, let me know if happy - be sure to use the latest 0.2.2 version of the plugin.

**Comment by JosephMcArthur** [comment]
Okay, I think the undefined bug is good to shut here. I've tested it on a few papers & they worked. I can see the view request thing working too - and that's a nice enhancement. 

The remaining issue highlighted here is:

> http://oab.test.cottagelabs.com/request/uDi3owjiczkTGEXdh the plugin finds no request at all

which still doesn't find the existing request. I can see you've used a t&f in your example above, and it worked for me so this doesn't happen for all t&f papers. Just wondering why it's happening here.

**Comment by markmacgillivray** [comment]
Ah - this is not an error, this is a problem.

The request page you link to has the URL as follows:

http://www.tandfonline.com/doi/full/10.1517/14656566.2016.1159298


Whereas when you are looking at that same article, you are probably seeing something like what I see, which is:

http://www.tandfonline.com/doi/abs/10.1517/14656566.2016.1159298?journalCode=ieop20


Note that it has a query parameter on the end? So I created a new request for it and it is here:

http://oab.test.cottagelabs.com/request/TezRFg5cErYjyzYzh


So you will see that is a new request because the URL is NOT the same. Unfortunately, the T&F site and some other publisher sites do not seem to be consistent in whether or not they include the query parameters.

I did previously try stripping query parameters from the URLs which would solve this problem for ones like this, BUT the problem then is that some other publisher sites use the query parameters to signify that the page is actually about a different article. This may be less common than the issue above, but is at least common enough for me to have seen it and hence changed back to the way we currently do.

We can only pick one of these for now - either we keep things as is now and some pages like this may not be recognised as the same, or we strip query parameters, solving problems like this but then potentially never being able to distinguish between pages that use query parameters to change their content.

We have discussed disambiguating what is on a URL by something like the DOI, but that is quite a change and has other consequences to consider. At any rate, given that what the plugin does now is record openness of URLs - not of DOIs - we can't make that change quickly. Also of course it would only help for things with DOIs (or whatever thing we chose to disambiguate on).

Also, even if we did as above, the real big problem with ignoring query parameters in future is that we could never use the plugin very well on google scholar or any other search-style page, because they almost always use query parameters to indicate the state of the page - we would be forever stuck thinking everyone is only on the homepage of google scholar, for example.

It is because of the above reason - that we could potentially lose a lot of functionality that we may later want - that I have reverted to the way it is now.

@JosephMcArthur let me know if you want this changed.

**Comment by JosephMcArthur** [comment]
Thought I tested the link changing - sorry. 

Okay, I'm happy to close this. All I'd suggest is we monitor this issue. I have a place to drop thoughts or sighting of the issue at #381.

**Comment by JosephMcArthur** [comment]
Do you mean when you went to the articles those requests are for, and
clicked the button, you couldn't find a request at all?

Are you using the new 2.1 plugin btw?

**Comment by markmacgillivray** [comment]
@JosephMcArthur who is that last comment aimed at? Doesn't seem to make sense in the context
